openapi: 3.0.0
info:
  version: 1.0.0
  title: My API
servers:
  - url: http://127.0.0.1:8787
    description: Local server
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: '123'
        name:
          type: string
          example: John Doe
        age:
          type: number
          example: 42
      required:
        - id
        - name
        - age
  parameters: {}
paths:
  /users/{id}:
    get:
      parameters:
        - schema:
            type: string
            minLength: 3
            example: '1212121'
          required: true
          name: id
          in: path
      responses:
        '200':
          description: Retrieve the user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Returns an error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                    example: 400
                  message:
                    type: string
                    example: Bad Request
                required:
                  - code
                  - message
